/**
 * Created by student on 27.03.16.
 */
define("modules/data",[],function (){
    console.log("data");
    return [
    {
        "id":1,
        "title":"Cake",
        "image":"Minion-Cake-icon.png",
        "count":0
    },
    {
        "id":2,
        "title":"Curious",
        "image":"Minion-Curious-icon.png",
        "count":0
    },
    {
        "id":3,
        "title":"Minion-Dancing",
        "image":"Minion-Dancing-icon.png",
        "count":0
    },
    {
        "id":4,
        "title":"Minion-Evil",
        "image":"Minion-Evil-3-icon.png",
        "count":0
    },
    {
        "id":5,
        "title":"Minion-Girl",
        "image":"Minion-Girl-icon.png",
        "count":0
    },
    {
        "id":6,
        "title":"Minion-Happy",
        "image":"Minion-Happy-icon.png",
        "count":0
    },
    {
        "id":7,
        "title":"Minion-Hello",
        "image":"Minion-Hello-icon.png",
        "count":0
    },
    {
        "id":8,
        "title":"Minion-Kungfu",
        "image":"Minion-Kungfu-icon.png",
        "count":0
    },
    {
        "id":9,
        "title":"Minion-Maid",
        "image":"Minion-Maid-icon.png",
        "count":0
    },
    {
        "id":9,
        "title":"Minion-Shout",
        "image":"Minion-Shout-icon.png",
        "count":0
    },
    {
        "id":10,
        "title":"Minion-Amazed",
        "image":"Minion-Amazed-icon.png",
        "count":0
    },
    {
        "id":11,
        "title":"Minion-Bananas",
        "image":"Minion-Bananas-icon.png",
        "count":0
    },
    {
        "id":12,
        "title":"Minion-Fruits",
        "image":"Minion-Fruits-icon.png",
        "count":0
    },
    {
        "id":13,
        "title":"Minion-Reading",
        "image":"Minion-Reading-icon.png",
        "count":0
    },
    {
        "id":14,
        "title":"Minion-Evil",
        "image":"Minion-Evil-icon.png",
        "count":0
    },
    {
        "id":15,
        "title":"Minion-Playing-Golf",
        "image":"Minion-Playing-Golf-icon.png",
        "count":0
    }
];

});